### ISSUE TITLE
Required end time selection in the web app

### ISSUE THREAD

**Issue by amineglr** [enshkn/BOUN-SWE-574-Fall-23-G2#100]
while adding a story user has to enter an endtime, we should fix this and remove the requirement

**Comment by gorkemkuyucu** [comment]
@mucahitugur i saw you fixed this issue and pull request is approved already. Can you confirm and if so close the issue by reffering to the pull request?

**Comment by mucahitugur** [comment]
It was fixed with https://github.com/enshkn/BOUN-SWE-574-Fall-23-G2/pull/158
