### ISSUE TITLE
Search by Tag in Web App

### ISSUE THREAD

**Issue by amineglr** [enshkn/BOUN-SWE-574-Fall-23-G2#104]
We should add a feature where a user clicks on a tag and lists all the stories with the same tag.

**Comment by gorkemkuyucu** [comment]
@amineglr current search api's query search already giving the results from tags. You intended to mention using that? If not we will need an update on the search or create another api to allow searching only tags since current search api gives all with the written wording (@hdenizdogan fyi).

**Comment by amineglr** [comment]
@gorkemkuyucu I should have clearify better. What I mean is not related directly related to the search feature. When a user views a story and decide to look for the stories thar have the same tag as it, they can click on that tag and it will lead then to a page where they can view the stories that has that tag. If it is not clear again, we can arrange a meeting and dlscuss the issue.

**Comment by gorkemkuyucu** [comment]
Ok it is clear now thanks. @hdenizdogan to have required functionality, we need an enhancement on backend side as i mentioned above. After that we can arrange the web app

**Comment by hdenizdogan** [comment]
Please check the mentioned issue @amineglr @gorkemkuyucu .
