### ISSUE TITLE
add delete location function while adding story

### ISSUE THREAD

**Issue by amineglr** [enshkn/BOUN-SWE-574-Fall-23-G2#112]
add delete location function while adding story

**Comment by amineglr** [comment]
commit : eb14ea71716c97314b49661ee15d4106df3b1263

**Comment by gokalpayaz** [comment]
1. i can add multiple locations
2. i can't delete it.

https://github.com/enshkn/BOUN-SWE-574-Fall-23-G2/assets/73962626/580ef48e-1194-485e-990a-9620db27a04b

**Comment by amineglr** [comment]
This bug is occurring because the delete icon is not visible all the way.
