### ISSUE TITLE
Copying the project dutluk to our repository

### ISSUE THREAD

**Issue by hdenizdogan** [enshkn/BOUN-SWE-574-Fall-23-G2#12]
Hello @enshkn , can you upload this project dutluk to the repo? here's the link: [dutluk](https://github.com/hdenizdogan/SWE-573-Spring-2023/)

**Comment by enshkn** [comment]
Done, please check the following link.https://github.com/enshkn/BOUN-SWE-574-Fall-23-G2
Sincerely.
