### ISSUE TITLE
Implement CI/CD pipeline

### ISSUE THREAD

**Issue by gokalpayaz** [enshkn/BOUN-SWE-574-Fall-23-G2#13]
We need a pipeline to test, build and deploy our application. This issue will be completed when CI/CD is able to build application.

**Comment by gokalpayaz** [comment]
@hdenizdogan, i created two pipelines (one for main, one for development branches) to build and deploy our applications to prod and test web applications respectively. 
I also created two web applications with the following urls:
dutluk.azurewebsites.net
dutluk-test.azurewebsites.net

please review the issue so that we can close it, provided that we are in an agreement.

**Comment by hdenizdogan** [comment]
I have checked both websites and they are running their respective branch. Thanks for the implementation!
