### ISSUE TITLE
Add poly lines, polygons and circles to the mobile app

### ISSUE THREAD

**Issue by amineglr** [enshkn/BOUN-SWE-574-Fall-23-G2#131]
Add polyline, polygon and circle drawing to the map.

**Comment by enshkn** [comment]
https://developers.google.com/maps/documentation/javascript/examples/drawing-tools this will be helpful, I hope.

**Comment by amineglr** [comment]
resolved on commit: dbbfd66ee351be6985e0f74b98dfc00e425b0a07
