### ISSUE TITLE
Change the timezone to "Europe/Istanbul"

### ISSUE THREAD

**Issue by hdenizdogan** [enshkn/BOUN-SWE-574-Fall-23-G2#156]
On the @JsonFormat annotations for the date values of startTimeStamp,endTimeStamp and createdAt have to be edited into "@JsonFormat(pattern = "yyyy-MM-dd HH:mm", timezone = "Europe/Istanbul")" in the classes StoryCreateRequest, StoryEditRequest(/request directory) and Story(/model directory) classes.

**Comment by enshkn** [comment]
all completed (StoryCreateRequest, StoryEditRequest and Story classes are updated) with the commit 848c68ee86b9d7cf6cf6d3d4681a6a0325ede05b
