### ISSUE TITLE
Response Model Format

### ISSUE THREAD

**Issue by amineglr** [enshkn/BOUN-SWE-574-Fall-23-G2#17]
@hdenizdogan Could you reformat the response model for api/story/all endpoint as 
{
    "status": 200,
    "success": true,
    "message": "success",
    "entity": {
       {
          "id": 2,
          "title":"title",
          "text": "text",
          ...
      }
    }
}

**Comment by hdenizdogan** [comment]
I can do this for all the responses so that we have a proper convention. What do you think?

**Comment by amineglr** [comment]
Great idea! It would be much better if all the responses had the same format.

**Comment by hdenizdogan** [comment]
Can you also share one for an unsuccessful response?

**Comment by hdenizdogan** [comment]
Note that I will be adding all API's like this. I will be also adding a count.

{
"status": 200,
"success": true,
"message": "success",
"count" : 1,
"entity": {
{
"id": 2,
"title":"title",
"text": "text",
...
}
}
}
