### ISSUE TITLE
Unhandled Exceptions

### ISSUE THREAD

**Issue by amineglr** [enshkn/BOUN-SWE-574-Fall-23-G2#185]
We should leave any unhandled exception. We should give some response to the user about what went wrong.  We need to show system error logs to the user.

**Comment by gorkemkuyucu** [comment]
Ant.design's message component is used. Since there are changes in most of the components, some miight be overlooked. Please review.

**Comment by gorkemkuyucu** [comment]
This issue can be closed since the the pull request is merged successfuly
