### ISSUE TITLE
Activity Feed Endpoint

### ISSUE THREAD

**Issue by amineglr** [enshkn/BOUN-SWE-574-Fall-23-G2#19]
@hdenizdogan Could you create and endpoint for Home page activity-feed? I know that we don't have the logic finalized yet, but I need it to finish the another issue(issue #20 ).

**Comment by hdenizdogan** [comment]
@amineglr I have added the api the the ec2 instance. Please double confirm.

**Comment by amineglr** [comment]
@hdenizdogan  /api/story/feed endpoint is ready. Thank you.
