### ISSUE TITLE
Null location names after editing a story

### ISSUE THREAD

**Issue by gorkemkuyucu** [enshkn/BOUN-SWE-574-Fall-23-G2#209]
After editing a story, null location names are send to database and shown afterwards. We should restrict sending null locations to the db.

**Comment by gorkemkuyucu** [comment]
Also current location names are not loaded to frontend on the WebApp and consequently editing (removing old ones) is not allowed. @gokalpayaz can you look at this issue?

**Comment by gokalpayaz** [comment]
> Also current location names are not loaded to frontend on the WebApp and consequently editing (removing old ones) is not allowed. @gokalpayaz can you look at this issue?

i'll take a look

**Comment by gokalpayaz** [comment]
@mucahitugur is it related to the issue you closed?

**Comment by mucahitugur** [comment]
@gokalpayaz no it is not related with my issue. My issue was about story detail.

**Comment by gokalpayaz** [comment]
@gorkemkuyucu , i haven't observed this behavior before. can you elaborate.

**Comment by gorkemkuyucu** [comment]
I think this issue is a duplicate and was solved with #188 and #189. I remember the problem was solved at that time. I'm closing this issue and adding a duplicate label.
