### ISSUE TITLE
False error message while uploading profile picture

### ISSUE THREAD

**Issue by hdenizdogan** [enshkn/BOUN-SWE-574-Fall-23-G2#215]
The profile picture is updated however an error is shown to the user even though the process has been completed successfully.

**Comment by gorkemkuyucu** [comment]
The problem is uploading a photo takes time and if the user clicks the button during this process error message has shown. Disabling the save button during loading is added.

**Comment by hdenizdogan** [comment]
@gorkemkuyucu this seems to continue on dev-react branch. Can you check it again?

**Comment by gorkemkuyucu** [comment]
Syntax of the catch part on handling photo upload was not right. Correcting it solved this issue.
