### ISSUE TITLE
Token inside User Model

### ISSUE THREAD

**Issue by amineglr** [enshkn/BOUN-SWE-574-Fall-23-G2#26]
@hdenizdogan Could you add token inside the user response?

**Comment by hdenizdogan** [comment]
Token is added for the login api on ec2 platform. Please double confirm.

**Comment by amineglr** [comment]
@hdenizdogan  Could use change the response model as :
{
   "status": 200,
    "success": true,
    "message": "success",
    "count": 0,
    "entity": {
       "token": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0IiwiZXhwIjoxNjk3NDI0NTI2LCJpYXQiOjE2OTczODg1MjZ9.AUNe4xVDa9KRQTzYqeovEudgFZQU5jdi7BbB_DKyjWw"
    }
  }

**Comment by hdenizdogan** [comment]
Development is complete. Can you double confirm?

**Comment by amineglr** [comment]
Could you change is like this: 
{
  "status": 200,
  "success": true,
  "message": "success",
  "count": 0,
  "entity": {
    "id": 1,
    "email": "string@example.com",
    "username": "string",
    "profilePhoto": null,
    "biography": null,
    "stories": [],
    "followers": [],
    "following": [],
    "token": "token"
  }
}

**Comment by hdenizdogan** [comment]
Development complete. Can you double confirm?

**Comment by hdenizdogan** [comment]
Development complete. Can you double confirm?
{
"status": 200,
"success": true,
"message": "success",
"count": 0,
"entity": {
"id": 1,
"email": "[string@example.com](mailto:string@example.com)",
"username": "string",
"profilePhoto": null,
"biography": null,
"stories": [],
"followers": [],
"following": [],
"token": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiZXhwIjoxNjk3NDMwODg4LCJpYXQiOjE2OTczOTQ4ODh9.5L7e3PMD-9WP_OOR-JFPou-cx1YXGxRHCOReadLSpuk"
}
}

**Comment by amineglr** [comment]
Thank you!
