### ISSUE TITLE
All button on the WebApp should have same design 

### ISSUE THREAD

**Issue by gorkemkuyucu** [enshkn/BOUN-SWE-574-Fall-23-G2#273]
Currently buttons have different looks. All buttons should use same component to be unified. This is also related with #91 and will help to design alignment with the mobile app.

**Comment by TevfikOzbilgin** [comment]
It is done but without alert buttons.

**Comment by gorkemkuyucu** [comment]
All different looking button styles are edited. Also form in the user page is changed to bootsrap to enhance ui.
