### ISSUE TITLE
Webapp Datetime picker enhancement

### ISSUE THREAD

**Issue by gorkemkuyucu** [enshkn/BOUN-SWE-574-Fall-23-G2#274]
Datetime picker should be updated. Ant.design or react bootsrap can be used for this. Time selection can be activated via a checkbox. this issue is related with the #91

**Comment by gorkemkuyucu** [comment]
@enshkn your improvement on the AddStory page involves this enhancement too?

**Comment by enshkn** [comment]
> @enshkn your improvement on the AddStory page involves this enhancement too?

Not yet , we have worked on component logic and its integration, but I will work on UI enhancements.

**Comment by gorkemkuyucu** [comment]
I'm assigning this issue to you then. If you need any help or have any comment, don't hesitate to write.

**Comment by enshkn** [comment]
It has done in react-date-picker-final branch when you are okay, I can commit then I can pull from upper branch to merge.

**Comment by enshkn** [comment]
I have completed UI enhancements with my issue #564 and pull requested with #565, from now on, this issue's subject is tracked by these two . So that this one is closed.
