### ISSUE TITLE
Slider for radius on WebApp

### ISSUE THREAD

**Issue by gorkemkuyucu** [enshkn/BOUN-SWE-574-Fall-23-G2#277]
Adding a slider for radius input can enhance usability on the WebApp. This enhancement should be used in add, edit, and search pages.

**Comment by TevfikOzbilgin** [comment]
ı dont understant its functionality in add and edit. Can you explain it?

**Comment by gorkemkuyucu** [comment]
In current app, user should write the radius to the box near circle. If the user do not write anything 5000m is defined as default but this info is not given to user also. What i meant was adding ant.design slider component (https://ant.design/components/slider) to there. The component looks like this: 
![image](https://github.com/enshkn/BOUN-SWE-574-Fall-23-G2/assets/120513132/543abc9c-4b38-4f9e-9aa3-95da47a9378f)
Limitations can be arranged on the component (min and max values). Showing predefined value will also help user

**Comment by TevfikOzbilgin** [comment]
Yes. I am implementing it as integers, but it is just usable in search. Is it?

**Comment by gorkemkuyucu** [comment]
Adding intergers as meters or float as km is both ok. It should be used in add story and edit story pages along with the search and timeline search pages.

**Comment by gorkemkuyucu** [comment]
Slider added to location selection under circle option. The value was changed to km and component arranged to allow float numbers.
