### ISSUE TITLE
like/unlike matrix vector multiplication conflict

### ISSUE THREAD

**Issue by hdenizdogan** [enshkn/BOUN-SWE-574-Fall-23-G2#300]
when a user likes a story for the first time the userWeight is sent as 1 however when that user dislikes it, as the userWeight is 0 it gives an error.

**Comment by enshkn** [comment]
done with the commits 7b87edff3a3c3ec0f9d2cd4981c073da0822a5b1, 9075bb499025a65ee7af0bf084eeaad407f43e80, 7d52230cf3d4f3ec1d334fcb599a939200bea0fa
