### ISSUE TITLE
user is not created with story-liked endpoint on rec engine

### ISSUE THREAD

**Issue by hdenizdogan** [enshkn/BOUN-SWE-574-Fall-23-G2#301]
when a user tries to like a story before adding a story it gives an error on rec engine side.

**Comment by enshkn** [comment]
done with the commits 7b87edff3a3c3ec0f9d2cd4981c073da0822a5b1, 9075bb499025a65ee7af0bf084eeaad407f43e80, 7d52230cf3d4f3ec1d334fcb599a939200bea0fa

**Comment by enshkn** [comment]
done with the commits 7b87edff3a3c3ec0f9d2cd4981c073da0822a5b1, 9075bb499025a65ee7af0bf084eeaad407f43e80, 7d52230cf3d4f3ec1d334fcb599a939200bea0fa
