### ISSUE TITLE
Integrate save Story same as like option

### ISSUE THREAD

**Issue by hdenizdogan** [enshkn/BOUN-SWE-574-Fall-23-G2#309]
Users now are able to stack and view their saved stories. Please enable react to use this functionality. It works similar to like story. Additional info can be found on swagger.

**Comment by gorkemkuyucu** [comment]
#398 and #399 are related to this issue. This issue can be closed following to copletion of those.

**Comment by gorkemkuyucu** [comment]
This issue is completed with the linked commits and issues (#399 and #398)
