### ISSUE TITLE
When a location is clicked on Search page the pin can't be removed 

### ISSUE THREAD

**Issue by hdenizdogan** [enshkn/BOUN-SWE-574-Fall-23-G2#320]
The pin has to be removed similar to AddStory.js

**Comment by gorkemkuyucu** [comment]
I'm not sure how to handle this. @gokalpayaz since you know more about map integration, can you handle this issue?

**Comment by gokalpayaz** [comment]
> I'm not sure how to handle this. @gokalpayaz since you know more about map integration, can you handle this issue?

ok i'll take a look
