### ISSUE TITLE
CheckUser Endpoint

### ISSUE THREAD

**Issue by amineglr** [enshkn/BOUN-SWE-574-Fall-23-G2#35]
@hdenizdogan Could you create an endpoint for autologin? I need a checkUser endpoint that I send the token to, and the endpoint returns the user if exists.

**Comment by hdenizdogan** [comment]
Hello, @amineglr except for login and register API's, the backend always checks the validity of the token so I believe this may not be necessary. That said, if you still need a checkUser API feel free to ask the backend team to provide it to you.
