### ISSUE TITLE
decade range

### ISSUE THREAD

**Issue by amineglr** [enshkn/BOUN-SWE-574-Fall-23-G2#354]
In order to add start decade and end decade for stories, we should add these properties to the story modal. After that we should implement this to the frontend as well.

**Comment by hdenizdogan** [comment]
please specify the story model. @mucahitugur @gokalpayaz @gorkemkuyucu @TevfikOzbilgin @enshkn

**Comment by hdenizdogan** [comment]
As we discussed on the meeting, an endDecade field will be created as string and this will also be implemented on the search logic. Please add the endDecade value to the mobile and react frontend for add, edit and view stories.

**Comment by hdenizdogan** [comment]
please confirm @amineglr , @gorkemkuyucu
