### ISSUE TITLE
Card Component Enhancement on WebApp

### ISSUE THREAD

**Issue by gorkemkuyucu** [enshkn/BOUN-SWE-574-Fall-23-G2#355]
We should enhance UI of the card component.

**Comment by gorkemkuyucu** [comment]
We need to add new field containing start of the story into the card component. @hdenizdogan can you give where are we gonna get this data from?

**Comment by hdenizdogan** [comment]
if you mean the text field containing the first 100 characters, then it is already implemented. the "text" field for the storyListResponse(all, recommended except for mystories) handles this. @gorkemkuyucu

**Comment by gorkemkuyucu** [comment]
Yeah I was asking about it. Thank you.
