### ISSUE TITLE
Attributes to add for backend about new time picker component.

### ISSUE THREAD

**Issue by enshkn** [enshkn/BOUN-SWE-574-Fall-23-G2#362]
After integrating the new time picker component and edit story story story into Dutluk, new attributes that will be used in the time picker component in both timeline search and edit story should be added to the story class. These are time expression, time type attributes. Time expression takes a string value and one of the values [moment, day, month, season, year, decade, decade+season] and time type takes one of the values [timePoint, timeInterval]. Below is a sample JSON of a request that the new time picker component will send in its raw form. Complete the necessary additions in this context @hdenizdogan . For your information @gokalpayaz.

Time Expression: year
TimeComponent.js:63 Time Type: timePoint
TimeComponent.js:64 Selected Year Start: 2016
TimeComponent.js:65 Selected Year End: 
TimeComponent.js:66 Selected Month Start: 4
TimeComponent.js:67 Selected Month End: 
TimeComponent.js:68 Selected Season Start: 
TimeComponent.js:69 Selected Season End: 
TimeComponent.js:70 Selected Decade Start: 
TimeComponent.js:71 Selected Decade End:

**Comment by hdenizdogan** [comment]
@gokalpayaz @hdenizdogan @enshkn @amineglr @mucahitugur @TevfikOzbilgin please note that this will require serious rework for all teams. On my end I have to change all services for add, edit, search, timeline search, nearby search, label search including the unit tests and all controllers. Mobile also has to be reworked completely for this update. Based on the time & resources we have, I doubt we can deliver on time. We should discuss this on a meeting ASAP.

**Comment by enshkn** [comment]
We have discussed these components on monday and we have distrubuted the responsibilities for integration and UI enhancement as you remember, nothing will be deleted from backend, you just add some new attributes to satisfy basic time picking mechanism which is a necessity @hdenizdogan

**Comment by amineglr** [comment]
As I remember from the customer feedback, we only had a problem with decade range which is only one field. For other components, frontend should find a way to work what we have from backend right now as I did for the mobile. There no need for only year selection, only month selection for example. These variations will affect all the search, timeline, add story and edit story which is a massive rework that we don't have time for. @enshkn @gokalpayaz @hdenizdogan

**Comment by enshkn** [comment]
When creating a story, there are very basic problems such as allowing only season selection in the season option and not allowing year selection, not being able to select the month, date picker not being available to select only the year, I think it is essential to make improvements here. @amineglr @gokalpayaz @hdenizdogan @gorkemkuyucu

**Comment by amineglr** [comment]
I specifically remember from the customer feedback that there are better ideas than choosing season, year, and season. I also got feedback from the customer on Monday while I showed the customer the timeline feature. The only request was end decade, decade range. There is no need to overwork, or rework since there are lots and lots of issues still open as we discuss. There are still main features that haven't been completed. The enhancement you mentioned would be nice if we had more time. No need to break something that works right now. @enshkn

**Comment by enshkn** [comment]
As I mentioned in my previous comment, we cannot cover even a simple resolution that we want to express as "the winter of 1965" while creating a story, I consider this to be a serious problem. As a requirement of our group formation, we can put it to a vote and decide, we created and shared the issues that these improvements will be made in the meeting we held on Monday.

**Comment by amineglr** [comment]
Let's meet then, at your earliest convenience.

**Comment by hdenizdogan** [comment]
please also refer to #341

**Comment by enshkn** [comment]
In the meeting held yesterday, it was decided to determine the attributes that should be added to the time picker model. The new time picker design will be worked on and the attributes needed will be determined and then implemented. After the new time picker design, a separate issue will be opened for this job.
