### ISSUE TITLE
Create Milestones of the Project

### ISSUE THREAD

**Issue by TevfikOzbilgin** [enshkn/BOUN-SWE-574-Fall-23-G2#37]
It is about to decide the milestones of the project and to assign the issues with them.

**Comment by TevfikOzbilgin** [comment]
Can not assign or label it because of login problems.

**Comment by amineglr** [comment]
Milestone 1 is done : https://github.com/enshkn/BOUN-SWE-574-Fall-23-G2/milestone/1

**Comment by enshkn** [comment]
Milestones were created.
