### ISSUE TITLE
Create delete-story endpoint .

### ISSUE THREAD

**Issue by enshkn** [enshkn/BOUN-SWE-574-Fall-23-G2#375]
When a story is deleted, the vector of that story must be deleted from the db. An endpoint will be created for this and then this endpoint will be integrated with Dutluk backend.

**Comment by enshkn** [comment]
delete story endpoint is ready you can reach the endpoint via "/delete-story" and simply you should give which id to delete with storyId key. Below an example of delete request of the story with 1001 id. For your information @hdenizdogan 
{  
    "storyId": "1001"
}

Note: Delete all story endpoint is not ready yet! I will create and present it soon.

**Comment by enshkn** [comment]
done with [5d4680b](https://github.com/enshkn/BOUN-SWE-574-Fall-23-G2/commit/5d4680b8579cf7469145c124248898254f6935d7)

**Comment by hdenizdogan** [comment]
please refer to #386 @enshkn
