### ISSUE TITLE
Implement SonarQube Analyze to development pipeline

### ISSUE THREAD

**Issue by gokalpayaz** [enshkn/BOUN-SWE-574-Fall-23-G2#38]
We must analyze our source code on every new commit made to development branch. If a bug is detected, build and deployment must be canceled.

**Comment by gokalpayaz** [comment]
I have implemented sonarqube analysis steps for both development and production pipelines. Results can be seen [here](https://sonarcloud.io/project/overview?id=enshkn_BOUN-SWE-574-Fall-23-G2)

@enshkn, @hdenizdogan  Please confirm if we can close the issue

**Comment by hdenizdogan** [comment]
Hello, Sonarqube implementation is working for both development and main branches.
