### ISSUE TITLE
Recommendation percentage should be showed on WebApp on recommendation page

### ISSUE THREAD

**Issue by gorkemkuyucu** [enshkn/BOUN-SWE-574-Fall-23-G2#383]
We need to show recommendation percentage to user depending on the story. This will help customer to understand how her or his interaction changes Karadut's response.

**Comment by hdenizdogan** [comment]
delivered on #381  you can view the field "percentage" on the story model for both list and singular.

**Comment by gorkemkuyucu** [comment]
I added showing recommendation percentage if the value is not null but could not test it since i have no percentage values on my local. @hdenizdogan or @enshkn can you check if it is working or not with proper values? Following to that, we can create a pull request.

**Comment by hdenizdogan** [comment]
I will be testing. @gorkemkuyucu

**Comment by gorkemkuyucu** [comment]
https://github.com/enshkn/BOUN-SWE-574-Fall-23-G2/tree/383-Recommendation-Percentage is the branch

**Comment by gorkemkuyucu** [comment]
@hdenizdogan i fixed the things we talked about. Can you check again?

**Comment by hdenizdogan** [comment]
I checked them. Please take a look at #417
