### ISSUE TITLE
Replace backend deploy by zip with deploy by image

### ISSUE THREAD

**Issue by gokalpayaz** [enshkn/BOUN-SWE-574-Fall-23-G2#39]
So far we have been creating zip artifact and then deploy using it. We must create backend image instead and then deploy it.

**Comment by gokalpayaz** [comment]
@hdenizdogan, i have copied the docker file and move the copy one level higher in the directory. That is because because of the location where code is executed, i either had to change the code content or make a copy of it. Since i didn't want to alter the way you use docker-compose, i did the later.
I also enabled tests in the dockerfile.

Both main and development pipelines are updated as well as related web apps.

@enshkn, @hdenizdogan , please review the issue so that we can close it.

**Comment by hdenizdogan** [comment]
Hello, @gokalpayaz , we also need to add the frontend as well, I will provide the .yml and the frontend directory to my branch in BE-1. Please note that the .env file has to be in the dutluk_frontend directory if you want to get the project up and running via Docker

**Comment by gokalpayaz** [comment]
Frontend is also added to .yml files.
