### ISSUE TITLE
Send IntegrationService methods the HttpServletRequest instead of User-Agent value

### ISSUE THREAD

**Issue by hdenizdogan** [enshkn/BOUN-SWE-574-Fall-23-G2#397]
the method should be called with (request,entity) instead of (request.userAgentValue,entity) for code readability.

**Comment by mucahitugur** [comment]
It is done by https://github.com/enshkn/BOUN-SWE-574-Fall-23-G2/commit/fbb3f8c36a62f38b945ed79cef9e4362a2203661
