### ISSUE TITLE
Developments for new time picker.

### ISSUE THREAD

**Issue by enshkn** [enshkn/BOUN-SWE-574-Fall-23-G2#441]
The new time picker is finally completed. This time picker is compatible with the existing backend structure and has been developed to include more time expression options. The flow of the new time picker is as follows. Firstly it asks the user to enter a timeType value, this value has two options as Time Point or Time Interval, the selected value is transferred to the backend as timePoint and timeInterval respectively. Then there is a dropdown menu to enter the timeExpression value. There are 7 options here. These are moment, day, month, month, season, year, decade, decade+season. The picker suitable for a total of 14 combinations is opened, for example, if the user has selected time point and month options, only year and month are seen in the opened picker. After the user selects a value, the frontend logician creates two string timeStamp values in a way that makes sense and provides maximum coverage. Again, the flag information required by the backend is also returned. Currently, all selected values are written with console.log. These will be removed after the integration is finished. Issue #423 and https://github.com/enshkn/BOUN-SWE-574-Fall-23-G2/tree/dev-react-date-picker addresses can be visited for review. When the frontend in this branch is stood up, it will be seen that the new picker is called at the end of the story-add page.

**Comment by enshkn** [comment]
the final component is can be reached here: 038d5448eb2e7af68630c3f1ec829e40029be7b2
The component logic is very easy; it transfers necessary states to upper components like AddStory etc. timeType, timeExpression, hourFlag, dateFlag, timeStampStart, timeStampEnd, seasonStart, seasonEnd, decadeStart, decadeEnd are the states that transfer to upper components. I will talk about how to use this component in today meeting for integration team.

**Comment by gorkemkuyucu** [comment]
Eline sağlık abi. These new developments are merged into first development-react, then the development branch. @enshkn can we close this issue?

**Comment by gokalpayaz** [comment]
@gorkemkuyucu, i will create a seperate issue for integrating it to timeline search. other than that i think it is ok to close. @enshkn , what do you say?

**Comment by enshkn** [comment]
I think it will be helpful to talk on this stuff tomorrow, ı have an idea which is simpler and more handy, anyway there will be need a separate issue to handle this task. An open issue can be created.

**Comment by hdenizdogan** [comment]
@enshkn I believe it can be closed now.

**Comment by enshkn** [comment]
This is issue is closed as planned, the new picker and related logic is integrated to project, new picker is designed to reuse easily.
