### ISSUE TITLE
Add verbalExpression attribute to story model.

### ISSUE THREAD

**Issue by enshkn** [enshkn/BOUN-SWE-574-Fall-23-G2#452]
A more understandable display method will be used in the date display of the stories. The timeType, timeExpression and date-time information collected from the user with the new DateTimePicker will be used to realise this goal. The new representation will be a string expression. Mobile and Web sides will be able to use this string value on their story carts. For this, a string value attribute with verbalDateExpression or any other name that makes sense to you should be added to the story model.

**Comment by hdenizdogan** [comment]
@enshkn  field added. please provide the verbal expression logic.

**Comment by enshkn** [comment]
I cannot transfer from here instead I will give you a link please download from there

**Comment by enshkn** [comment]
Please check here, https://github.com/enshkn/verbalExpressionFunction

**Comment by enshkn** [comment]
@hdenizdogan can you get the function?

**Comment by enshkn** [comment]
After you will get the function, the issue can be closed.

**Comment by enshkn** [comment]
We have tested and seen that the verbal expression function is working well. We can close this issue. To express verbalExpression in frontend there will need another issues for teams.
