### ISSUE TITLE
Delete Button is not showing on MyStories Page on WebApp

### ISSUE THREAD

**Issue by gorkemkuyucu** [enshkn/BOUN-SWE-574-Fall-23-G2#466]
I noticed that the delete button is not showing on the my stories page even though it is included on the code. @gokalpayaz i think this is occuring because of the new card compenent integration. Can you check?

**Comment by gokalpayaz** [comment]
> I noticed that the delete button is not showing on the my stories page even though it is included on the code. @gokalpayaz i think this is occuring because of the new card compenent integration. Can you check?

Ok will do
