### ISSUE TITLE
Like and Text Fields on MyStories Page on WebApp

### ISSUE THREAD

**Issue by gorkemkuyucu** [enshkn/BOUN-SWE-574-Fall-23-G2#467]
It gives like list instead of like number and text field also gives values like <p> inside the text field which means it is returning rich text when response is requested from api/story/fromUser. Since web app is using same component for all story listing pages, response should be same.

**Comment by gorkemkuyucu** [comment]
@amineglr is changing return of rich test for this api changes mobile app's functionality in somehow?

**Comment by amineglr** [comment]
Hi, backend has a different logic for my stories. It doesnt parse the html content. So in order to overcome this I put the text field inside an html parser just like story details text viewing. You can do this your side as well

**Comment by gorkemkuyucu** [comment]
@gokalpayaz i think you solved this issue. Can you confirm and close it if so?

**Comment by gokalpayaz** [comment]
> @gokalpayaz i think you solved this issue. Can you confirm and close it if so?

Yeap, closing
