### ISSUE TITLE
implement pipeline for nodejs frontend

### ISSUE THREAD

**Issue by gokalpayaz** [enshkn/BOUN-SWE-574-Fall-23-G2#51]
Since we have added frontend files to the repository, we must add two pipelines for frontend (test&prod)

**Comment by gokalpayaz** [comment]
I have implemented pipeline to build and deploy our frontend application for test and prod web applications.
This also means that i have created two web apps to host those application.

@hdenizdogan , please review so that we can close

**Comment by hdenizdogan** [comment]
can you share the links via discord? @gokalpayaz

**Comment by gokalpayaz** [comment]
Sure i will. Also i'll put them here as well:
dutluk-fe-prod.azurewebsites.net
dutluk-fe-test.azurewebsites.net

please note that, prod is not running as main branch doesn't have frontend files as we speak.

**Comment by hdenizdogan** [comment]
Alright, we need the issue https://github.com/enshkn/BOUN-SWE-574-Fall-23-G2/issues/53 to be closed so that your pipelines can be aligned to the azure endpoints.

**Comment by gokalpayaz** [comment]
#53 is completed, therefor i close the issue.
