### ISSUE TITLE
Add verbalExpression field to the single and multiple story views on React

### ISSUE THREAD

**Issue by hdenizdogan** [enshkn/BOUN-SWE-574-Fall-23-G2#514]
verbalExpression field is a string where we contain all the date values in a verbose sentence. What we expect from the frontend is that if the verbalExpression field is not null, return the date fields as is. In the case of verbalExpression is not null, only the verbalExpression field should be visible to the user. The reason why is that we don't lose the functionality through this transition of date fields viewing.

**Comment by gorkemkuyucu** [comment]
If there is a verbal expression, it will be showed and if not other not null values will be showed. The change requested in this issue was completed with the referred commit.
