### ISSUE TITLE
Change of endpoints on react frontend

### ISSUE THREAD

**Issue by hdenizdogan** [enshkn/BOUN-SWE-574-Fall-23-G2#53]
On the react project, the endpoints are written like this "http://${process.env.REACT_APP_BACKEND_URL}:8080/api/user/profile" but all endpoints should be like this in order to ensure parametric endpoints. "${process.env.REACT_APP_BACKEND_URL}/api/user/profile" . Please update all endpoints based on this example on the development-react branch. @gokalpayaz pls follow this issue so that the ci/cd parameters can be written accordingly.

**Comment by gorkemkuyucu** [comment]
Changing api endpoints to allow usage of http or https and port number by only changing .env file is done.

**Comment by gokalpayaz** [comment]
Hi team, i've checked the web sites and requests are not sent to correct URLs. Can we get together to check please?
