### ISSUE TITLE
"You liked the comment" message for unliking comment

### ISSUE THREAD

**Issue by hdenizdogan** [enshkn/BOUN-SWE-574-Fall-23-G2#534]
![image](https://github.com/enshkn/BOUN-SWE-574-Fall-23-G2/assets/83790733/e6559c2f-9aac-44c8-9e98-5e11aac6d282)
we see the same message for both liking and unliking the comment. Your assistance is required. @gorkemkuyucu

**Comment by gorkemkuyucu** [comment]
It would be great to have a isLiked api for the comments. This will help implementing same logic with the other parts of the code.

**Comment by gorkemkuyucu** [comment]
I opened a new issue related to that (#569 )

**Comment by gorkemkuyucu** [comment]
This issue is completed by creating a new component for comment listing. This was needed for updating each comment separetly. Also button UI enhancements are completed.
