### ISSUE TITLE
EditStory Page Enhancements and Fixes on WebApp

### ISSUE THREAD

**Issue by gorkemkuyucu** [enshkn/BOUN-SWE-574-Fall-23-G2#545]
Considering updates on add story page, edit story is outdated right now. We should enhance edit story page. Also bugs on the page should be fixed.

**Comment by gorkemkuyucu** [comment]
@enshkn i could not handled selecting previous time type and expression. Could you help about it?

**Comment by gorkemkuyucu** [comment]
![image](https://github.com/enshkn/BOUN-SWE-574-Fall-23-G2/assets/120513132/15b86b89-eb1d-4a16-a2fd-8e4d4097d056)
I added these fields but those are not editing required fields.

**Comment by gorkemkuyucu** [comment]
@hdenizdogan i don't think that locations are edited on the backend according to swagger. Can you check this problem? @amineglr do you encountered this problem too?

**Comment by gorkemkuyucu** [comment]
@amineglr can you explain how you are processing locations? On web app side we are saving same index to the fields like isPolygon or isPolyline and this helps to group the points after saving. But i think we are showing only points on the mobile app side. @gokalpayaz can explain further since he developped web app side if you need more explaination. Anyhow we need to handle using same way to show same location types on the map.

**Comment by hdenizdogan** [comment]
> @hdenizdogan i don't think that locations are edited on the backend according to swagger. Can you check this problem? @amineglr do you encountered this problem too?

I believe it is fixed. please refer to #546

**Comment by enshkn** [comment]
> ![image](https://private-user-images.githubusercontent.com/120513132/293276170-15b86b89-eb1d-4a16-a2fd-8e4d4097d056.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NDUzMTQsIm5iZiI6MTcwMzg0NTAxNCwicGF0aCI6Ii8xMjA1MTMxMzIvMjkzMjc2MTcwLTE1Yjg2Yjg5LWViMWQtNGExNi1hMmZkLThlNGQ0MDk3ZDA1Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOVQxMDE2NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Mzc3OTJkN2Y2OTA1MjM2NWVjZDAwMzk4ZjYwNDE5ZDQxYjQwMjYyM2VmOWYxZWI4MDA2MWJlMWNmMTRlODAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kobMFOE4ktQGUya0YZbNjqQDp7cMmqMeFx4zvxcqdw4) I added these fields but those are not editing required fields.

do you need still help here, we can analyze it.

**Comment by gorkemkuyucu** [comment]
@hdenizdogan yes that problem is solved and now we can edit locations with the code i already commited. Thanks.

**Comment by gorkemkuyucu** [comment]
@enshkn yes i still need help because even those are not required fields we demand user to select at least one. Additionally we should show user pre-selected date and allow editing it. If user selects different resolution, previous field should be set to null and related flags should be updated. I could not arrange showing previously selected timeType and timeExpression

**Comment by enshkn** [comment]
in which branch and page are you developing, so that I can analyse and hope to find a solution.

**Comment by gorkemkuyucu** [comment]
The brach is [545-EditStory-Update-and-Fixes](https://github.com/enshkn/BOUN-SWE-574-Fall-23-G2/tree/545-EditStory-Update-and-Fixes) and pages is EditStory.js. We can look together too if that suits you.

**Comment by gorkemkuyucu** [comment]
Ok let me share updates about this issue. We disscussed with @enshkn and understood that lots of improvements are needed in order to show user the previous date on the newly developped DateTimePicker. Since there is not much time left, we decided to show user the previous date. Only remaining problem is we need to change how backend is processing date fields on story/edit api. @hdenizdogan can you change backend side to delete previous date id there is data send by the picker and if not keep the same date?

**Comment by gorkemkuyucu** [comment]
This page is almost completed but i noticed some bugs before commiting the last code. Since this issue is closed, I will address them in another issue.
