### ISSUE TITLE
Locations can't be edited for edit story api

### ISSUE THREAD

**Issue by hdenizdogan** [enshkn/BOUN-SWE-574-Fall-23-G2#546]
new locations to be added doesn't carry the story information. it should be added via a for each loop.

**Comment by gorkemkuyucu** [comment]
I tested locally on swagger and previous locations are not removed, new send ones added to the list. So this is not solved entirely. We should delete previous ones. Here is the related part of an edited story location: 
![image](https://github.com/enshkn/BOUN-SWE-574-Fall-23-G2/assets/120513132/597058e8-5e15-4dc8-9bcf-15e1802b3d2f)

**Comment by gorkemkuyucu** [comment]
![image](https://github.com/enshkn/BOUN-SWE-574-Fall-23-G2/assets/120513132/07e2cdad-3af5-4124-b69b-75c8a09abd4a)
Image could not be uploaded in the previous response. I'm sharing it again.

**Comment by gorkemkuyucu** [comment]
Yes, i tested it on the swagger and problem seems to be solved. Eline sağlık.
