### ISSUE TITLE
Story Details Page Layout and UI Enhancement

### ISSUE THREAD

**Issue by TevfikOzbilgin** [enshkn/BOUN-SWE-574-Fall-23-G2#551]
The layout of the code, thus the UI look of the page will be improved. Code quality and logical improvements will be applied.

**Comment by TevfikOzbilgin** [comment]
The page is aligned with the fields it has. Google Map, and the Form components are in the same row.

**Comment by gorkemkuyucu** [comment]
@TevfikOzbilgin i could not see the related commit, it think that you are not referred to this issue in the explanation. Could you connect it to this issue?
