### ISSUE TITLE
Correction on verbalExpression method needed

### ISSUE THREAD

**Issue by hdenizdogan** [enshkn/BOUN-SWE-574-Fall-23-G2#562]
The values are wrong for year and month parsing. Note that the value of dates can be `dd/MM/yyyy HH:mm`,`dd/MM/yyyy`,`MM/yyyy`,`yyyy`. subString process should be handled by the dateService.

**Comment by enshkn** [comment]
I will add my tests results below

**Comment by enshkn** [comment]
timeType = timePoint
timeExpression = moment
![Screenshot 2023-12-30 at 12 36 28](https://github.com/enshkn/BOUN-SWE-574-Fall-23-G2/assets/96254574/7ec7abf3-83e1-4cbe-a418-3f5056dcf185)

this is ok!

**Comment by enshkn** [comment]
timeType = timePoint
timeExpression = day

![Screenshot 2023-12-30 at 12 37 09](https://github.com/enshkn/BOUN-SWE-574-Fall-23-G2/assets/96254574/ab714a0c-30ac-400d-948b-776f653c252b)

the day value shows null, there is a bug

**Comment by enshkn** [comment]
timeType = timePoint
timeExpression = day

![Screenshot 2023-12-30 at 12 38 20](https://github.com/enshkn/BOUN-SWE-574-Fall-23-G2/assets/96254574/d0c93fc3-f2dc-4759-93a7-c63cd78d1ffd

there is a bug: months name shall be in a dict with key 01,02,03 etc then

**Comment by enshkn** [comment]
All seems ok for now, we can close the issue ! Fronend and mobile teams shall add verbalExpression to story details for this purpose another issue shall be open!

**Comment by hdenizdogan** [comment]
Issue closed based on your comment. @enshkn
