### ISSUE TITLE
StoryDetail Page Update on WebApp

### ISSUE THREAD

**Issue by gorkemkuyucu** [enshkn/BOUN-SWE-574-Fall-23-G2#584]
Story Detail page is currently very outdated. We need to improve UI and add new fields. This is a high priority issue since if the funcinality is not shown to customer, some questions can be raised. We should consider screen real estate too during this enhancement.

**Comment by TevfikOzbilgin** [comment]
You can tell about the required updates.

**Comment by hdenizdogan** [comment]
@mucahitugur please review the test of StoryDetails page after this issue is closed.
