### ISSUE TITLE
Create a kanban board on github

### ISSUE THREAD

**Issue by hdenizdogan** [enshkn/BOUN-SWE-574-Fall-23-G2#6]
Research on kanban board for github is needed.

**Comment by hdenizdogan** [comment]
The project admin @enshkn has to create a new project for the kanban board.

**Comment by enshkn** [comment]
Kanban board has initialized. You can reach via the following link. 

https://github.com/users/enshkn/projects/3

Sincerely.

**Comment by hdenizdogan** [comment]
Hello @enshkn , can you double check on your end? I couldn't access the kanban board.

**Comment by enshkn** [comment]
> Hello @enshkn , can you double check on your end? I couldn't access the kanban board.

I have invited all members to project's kanban board as admin , please check @hdenizdogan @amineglr @mucahitugur @gokalpayaz @TevfikOzbilgin @gorkemkuyucu

**Comment by hdenizdogan** [comment]
It is visible however I am seeing only 4 issues in total. It is probably showing only the issues you created.

**Comment by enshkn** [comment]
Everybody is caring admin privileges for now,I think upcoming issues will
be displayed, can you try?
Regards.

16 Eki 2023 Pzt 12:38 tarihinde Hasan Deniz Doğan ***@***.***>
şunu yazdı:

**Comment by gokalpayaz** [comment]
The issues we don't see are the ones that are those which has no project specified. If we specify, we should be able to see them in the kanban board

**Comment by gokalpayaz** [comment]
I have added all to the project and can confirm they are all present in both roadmap and kanban board
