### ISSUE TITLE
Recommended page should be added to the web application

### ISSUE THREAD

**Issue by amineglr** [enshkn/BOUN-SWE-574-Fall-23-G2#70]
The new feature which shows the user the recommended stories should be implemented to the web application.

**Comment by gorkemkuyucu** [comment]
@hdenizdogan I need api endpoint fpr recommended page. Can you provide?

**Comment by hdenizdogan** [comment]
hello, so far we haven't implemented the recommendation logic yet, however you can use api/story/feed which is currently shows all stories for now.

**Comment by gorkemkuyucu** [comment]
Ok thank you for the quick reply
