### ISSUE TITLE
Add story navigation

### ISSUE THREAD

**Issue by amineglr** [enshkn/BOUN-SWE-574-Fall-23-G2#72]
In the web application, after the user adds a story we should navigate to the home page not profile page.

**Comment by gokalpayaz** [comment]
implemented with 693b6ee937305f592e6ca3b6cbcf08e94685241f

**Comment by gokalpayaz** [comment]
@amineglr  could you review and close if agreed please?

**Comment by amineglr** [comment]
Checked the code, it seems fine. We can close the issue.
