### ISSUE TITLE
Web app frontend design fixes

### ISSUE THREAD

**Issue by amineglr** [enshkn/BOUN-SWE-574-Fall-23-G2#91]
We should make design of the web app to be consistent to the mobile app design.  This includes tabbar color changes and adding the new pages, making the story card component to be more pleasant.

**Comment by gorkemkuyucu** [comment]
Hey @amineglr, can you clarify which pages you wanted to be added to webApp? (I am not sure if they are already added or not, this is why i am asking). 

Also can you share some images from mobile app for us to look at? In this way we can search for similar components.

**Comment by amineglr** [comment]
hi, what I mean is the story card(preview of the story) that is basically in every page, could be more understandable. We have a big area in the web app so we could put the first story image on one side of the card and we can put the other information like title, location, tags and author to the other side. Other thing is that webapp color right now is orange and we want the mobile app and web app design to be consistent so we can make the primary color of the web app blue. I am adding the mobile app pages for some inspo. 
![Screenshot_1700770826](https://github.com/enshkn/BOUN-SWE-574-Fall-23-G2/assets/50747015/279f2a0b-1f66-4726-90bb-d3f390ff54ca)
![Screenshot_1700770841](https://github.com/enshkn/BOUN-SWE-574-Fall-23-G2/assets/50747015/69e81b7a-9681-4e06-89be-d47d2dd8a3b9)
![Screenshot_1700770847](https://github.com/enshkn/BOUN-SWE-574-Fall-23-G2/assets/50747015/2cce7dd1-7d23-4eca-af56-bc879cf93b17)
![Screenshot_1700770854](https://github.com/enshkn/BOUN-SWE-574-Fall-23-G2/assets/50747015/9aa8c867-2c59-44a1-a60b-b50c2db50d37)
![Screenshot_1700770856](https://github.com/enshkn/BOUN-SWE-574-Fall-23-G2/assets/50747015/fc879532-181a-4234-bc68-44b4db1ac401)
![Screenshot_1700770865](https://github.com/enshkn/BOUN-SWE-574-Fall-23-G2/assets/50747015/521214dc-a0b8-48c1-89f9-b39d94f87103)

**Comment by gorkemkuyucu** [comment]
Several issues will be opened in order to cover scope of this issue.

**Comment by TevfikOzbilgin** [comment]
Changed the index according to it
